#!/usr/bin/python
import argparse
import subprocess
import sys

from lxml import etree


def parse_args():
    parser = argparse.ArgumentParser(
        description='Create Crowbar deploy node',
        )
    parser.add_argument(
        'uri',
        metavar='URI',
        help='libvirt URI to connect to',
        )
    parser.add_argument(
        'network',
        metavar='NETWORK',
        help='network to use as isolated network',
        )
    parser.add_argument(
        'name',
        metavar='NAME',
        help='unique name of this crowbar cluster',
        )
    parser.add_argument(
        'number',
        type=int,
        metavar='NUMBER',
        help='number to identify this node in cluster',
        )
    args = parser.parse_args()
    return args


def template(args):
    tree = etree.fromstring("""
<domain type='kvm'>
  <name>XYZZY</name>
  <memory>1048576</memory>
  <os>
    <type arch='x86_64' machine='pc-0.12'>hvm</type>
    <boot dev='network'/>
    <boot dev='hd'/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <pae/>
  </features>
  <clock offset='utc'/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>restart</on_crash>
  <devices>
    <emulator>/usr/bin/kvm</emulator>
    <disk type='file' device='disk'>
      <driver name='qemu' type='raw'/>
      <source file='XYZZY'/>
      <target dev='sda' bus='sata'/>
    </disk>
    <interface type='network'>
      <source network='XYZZY'/>
      <model type='e1000'/>
    </interface>
    <serial type='pty'>
      <target port='0'/>
    </serial>
    <console type='pty'>
      <target type='serial' port='0'/>
    </console>
    <input type='mouse' bus='ps2'/>
    <graphics type='vnc' port='-1' autoport='yes'/>
  </devices>
</domain>
""")
    (name_elem,) = tree.xpath('/domain/name')
    name_elem.text = 'crow-{name}-node-{number}'.format(
        name=args.name,
        number=args.number,
        )

    assert '/' not in args.name
    # evil hardcoded path
    hdd_path = '/var/lib/libvirt/images/crow-{name}-node-{number}.img'.format(
        name=args.name,
        number=args.number,
        )
    (hdd_elem,) = tree.xpath(
        '/domain/devices/disk[@device="disk"]/source',
        )
    hdd_elem.set('file', hdd_path)

    assert args.network.startswith('isolated')
    (network_elem,) = tree.xpath(
        '/domain/devices/interface[@type="network"]'
        + '/source[@network="XYZZY"]',
        )
    network_elem.set('network', args.network)
    s = etree.tostring(tree)
    assert 'XYZZY' not in s
    return s


def main():
    args = parse_args()

    assert args.number < 10, \
        'cleanup is currently hardcoded to max 9 nodes'

    subprocess.check_call(
        args=[
            'virsh',
            '--connect={uri}'.format(uri=args.uri),
            'vol-create-as',
            '--pool=default',
            '--capacity=10G',
            '--format=raw',
            '--name=crow-{name}-node-{number}.img'.format(
                name=args.name,
                number=args.number,
                ),
            ],
        )

    node_xml = template(args)
    define_args = [
        'virsh',
        '--connect={uri}'.format(uri=args.uri),
        'define',
        '/dev/stdin',
        ]
    p = subprocess.Popen(
        args=define_args,
        stdin=subprocess.PIPE,
        )
    p.communicate(input=node_xml)
    ret = p.wait()
    if ret != 0:
        raise subprocess.CalledProcessError(ret, define_args)

    subprocess.check_call(
        args=[
            'virsh',
            '--connect={uri}'.format(uri=args.uri),
            'start',
            '--domain=crow-{name}-node-{number}'.format(
                name=args.name,
                number=args.number,
                ),
            ],
        )


if __name__ == '__main__':
    sys.exit(main())
